use_frameworks!
ENV["COCOAPODS_DISABLE_STATS"] = "true"

target 'RasLogger_Example' do
  pod 'RasLogger', :path => '../'

  target 'RasLogger_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.9.3'
  pod 'Nimble', '~> 4.1.0'
  end
end
