use_frameworks!

target 'RasLogger_Example' do
  pod 'RasLogger', :path => '../'

  target 'RasLogger_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
